name: semgrep 
version: 1.25.0 
origin: https://github.com/Decurity/semgrep-smart-contracts # optional
info: Find patterns of vulnerabilities in smart contracts based on actual DeFi exploits as well as gas optimization rules that can be used as a part of the CI pipeline.
image: smartbugs/toolname:1.25.0 # id of Docker image (mandatory)
bin: scripts # folder with programs that will be accessible in the Docker container
# add the section below if the tool is able to analyse Solidity source code
solidity:
    entrypoint: "'$BIN/do_solidity.sh' '$FILENAME' '$TIMEOUT' '$BIN'"
    solc: yes
